name: Accessibility Check

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  accessibility:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # or the version you need

    - name: Install dependencies
      run: npm install

    - name: Run Axe Linter
      run: npx axe-linter # Replace this with your specific command to run Axe Linter