name: PHPCS check
on:
  push

env:
  GH_TOKEN: ${{ github.token }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  phpcs:
    name: PHPCS check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.4"
          ini-values: "memory_limit=1G"
          coverage: none
          tools: cs2pr

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v2"

      - name: Run PHPCS checks
        # Get the changed files from the PR via Github CLI.
        # `grep` to only PHP files then remove deleted files via `find`.
        # Run `phpcs` on the remaining files and pass output to `cs2pr`.
        run: |
          gh pr diff ${{ github.event.number }} --name-only | grep .php | xargs find 2> /dev/null | cat
          gh pr diff ${{ github.event.number }} --name-only | grep .php | xargs find 2> /dev/null | xargs vendor/bin/phpcs -nq --report=checkstyle --report-full --report-checkstyle=./phpcs-report.xml | cs2pr
